services:
  - type: web
    name: telegram-footer-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN
      - key: CHANNEL_ID
        value: -1001234567890  # Your channel's numeric ID
